blog/urls.py
from django.urls import path
from . import views
from users import views as user_views
from .views import *
from django.conf.urls import url

urlpatterns = [
    path('', views.home_view,name='blog-home'),
    url(r'^ajaxtest/', views.get_post, name='ajaxtest'),
    path('<pk>', views.home_view,name='post-open'),
    path('mobile/notifications', views.notifications,name='notifications'),
    path('mobile/messages', views.messages,name='messages'),
    path('user/<str:username>', views.get_user_information,name='user-posts'),
    path('user/<str:username>/<str:view>', views.get_user_information,name='user-posts'),
    path('group/<str:name>', views.get_group_information,name='group-posts'),
    path('group/<str:name>/<str:view>', views.get_group_information,name='group-posts'),
    path('topic/<topic>', views.getTopic,name='topic-posts'),
    path('post/item/<pk>/', views.getPost,name='post-detail'),
    path('search/<str:query_result>', views.search,name='search'),
    path('post/<int:pk>/update', PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(),name='post-delete'),
    path('post/test', PostUpdateView.as_view(),name='post-open2'),
    path('post/new', PostCreateView.as_view(),name='post-create'),
    path('test/', views.test,name='test'),
    path('about/', views.about,name='blog-about'),

]

django_web_project/urls.py
from django.contrib import admin
from django.conf.urls import include, handler404, handler500
from django.urls import include, path
from django.contrib.auth import views as auth_views
from users import views as user_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('super-auth/', admin.site.urls),
    path('register/', user_views.register,name='register'),
    path('profile/', user_views.profile,name='profile'),
    path('group/edit/<str:name>', user_views.group,name='group'),
    path('group/manage', user_views.group_manager,name='group_manager'),
    path('group/manage/new', user_views.group_new,name='group-new'),
    path('feedback/', user_views.feedback,name='feedback'),
    path('about/', user_views.about,name='about'),
    path('privacy/', user_views.privacy,name='privacy'),
    path('legal/', user_views.legal,name='legal'),
    path('welcome/', user_views.welcome,name='welcome'),
    path('terms_of_service/', user_views.terms_of_service,name='terms_of_service'),
    path('versions/', user_views.versions,name='patch_notes'),
    path('feedback/sent', user_views.feedback_sent,name='feedback-sent'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('', include('blog.urls')),
]

handler404 = user_views.handler404
handler500 = user_views.handler500

if(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages
from PIL import Image
from .models import *
from users.models import *

class Topic(models.Model):
    title = models.CharField(max_length = 20)
    date_posted = models.DateTimeField(default = timezone.now)
    def __str__(self):
        return (self.title)

    def get_absolute_url(self):
        return reverse('post-detail',kwargs={'pk' : self.pk})

class Post(models.Model):
    title = models.CharField(max_length = 100,blank=True)
    image = models.ImageField(default = 'default.jpg', upload_to='post_pics')
    video = models.FileField(upload_to='video_files', null=True, verbose_name="Video", blank=True)
    audio = models.FileField(upload_to='audio_files', null=True, verbose_name="Audio", blank=True)
    content = models.TextField(max_length = 500, blank=True)
    date_posted = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    topics = models.ManyToManyField(Topic, blank=True, symmetrical=False)
    people = models.ManyToManyField(User, blank=True,related_name='people', symmetrical=False)
    reply = models.ForeignKey("self", on_delete = models.CASCADE, blank=True, default = "self", null=True)
    repost = models.ForeignKey("self", on_delete = models.CASCADE,related_name='reposts', blank=True, null=True)
    group = models.ForeignKey(Group, on_delete = models.CASCADE, blank=True, null=True)
    link = models.CharField(max_length = 150,blank=True)

    def __str__(self):
        return (f'{self.author} : {self.content}')

    def get_absolute_url(self):
        return reverse('post-detail',kwargs={'pk' : self.pk})

    def cast_empty_reference(self):
        self.reply = self
        super().save()



    def save(self, **kwargs):
        super().save()
        #Resize Images upon Profile creation
        img = Image.open(self.image.path)
        if (img.height > 1920 and img.width > 1080):
            output_size = (1080,720)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Message(models.Model):
    image = models.ImageField(default = 'default.jpg', upload_to='post_pics')
    video = models.FileField(upload_to='video_files', null=True, verbose_name="Video", blank=True)
    audio = models.FileField(upload_to='audio_files', null=True, verbose_name="Audio", blank=True)
    content = models.TextField(max_length = 500, blank=True)
    date_posted = models.DateTimeField(default = timezone.now)
    recepient = models.ForeignKey(User, on_delete = models.CASCADE,related_name='msgrecepient', blank=True, null=True)
    sender = models.ForeignKey(User, on_delete = models.CASCADE,related_name='msgsender', blank=True, null=True)
    topics = models.ManyToManyField(Topic, blank=True, symmetrical=False)
    people = models.ManyToManyField(User, blank=True, symmetrical=False)
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return (f'Message From {self.sender} : To {self.recepient}')

    def get_absolute_url(self):
        return reverse('post-detail',kwargs={'pk' : self.pk})

    def cast_empty_reference(self):
        self.reply = self
        super().save()

    def save(self, **kwargs):
        super().save()
        #Resize Images upon Profile creation
        img = Image.open(self.image.path)
        if (img.height > 1920 and img.width > 1080):
            output_size = (1080,720)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    image = models.ImageField(default = 'default.jpg', upload_to='post_pics')
    content = models.TextField(max_length = 500)
    date_posted = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return (f"Re: {self.post.title}")

    def save(self, **kwargs):
        super().save()
        #Resize Images upon Profile creation
        img = Image.open(self.image.path)
        if (img.height > 1920 or img.width > 1080):
            output_size = (1080,720)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def create_self(self, author, post, image, content):
        obj = self.create(author=author, post=post, image=image, content=content)
        return obj

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return (f"{self.post.title}")

class Activity(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, default=None)
    date = models.DateTimeField(default = timezone.now)
    type = models.IntegerField(default=0)
    group = models.ForeignKey(Group, on_delete = models.CASCADE, blank=True, null=True)

    def __str__(self):
        return (f"{self.author}")

class Notification(models.Model):
    recepient = models.ForeignKey(User, on_delete = models.CASCADE,related_name='recepient', blank=True, null=True)
    sender = models.ForeignKey(User, on_delete = models.CASCADE,related_name='sender', blank=True, null=True)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, default=None,blank=True, null=True)
    type = models.IntegerField(default=0)
    confirmed = models.BooleanField(default=False)
    first_seen = models.BooleanField(default=False)
    date_posted = models.DateTimeField(default = timezone.now)
    group = models.ForeignKey(Group, on_delete = models.CASCADE, blank=True, null=True)

    def __str__(self):
        return (f"To {self.recepient} From {self.sender}")

    def save(self, **kwargs):
        super().save()


class Request(models.Model):
    recepient = models.ForeignKey(User, on_delete = models.CASCADE,related_name='requestant', blank=True, null=True)
    sender = models.ForeignKey(User, on_delete = models.CASCADE,related_name='requester', blank=True, null=True)
    confirmed = models.BooleanField(default=False)
    accepted = models.BooleanField(default=False)
    date_posted = models.DateTimeField(default = timezone.now)
    type = models.IntegerField(default=0)
    group = models.ForeignKey(Group, on_delete = models.CASCADE, blank=True, null=True)

    def __str__(self):
        return (f"To {self.recepient} From {self.sender}")

    def save(self, **kwargs):
        super().save()

class Report(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, default=None,blank=True, null=True)
    author = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)
    confirmed = models.BooleanField(default=False)
    date_posted = models.DateTimeField(default = timezone.now)

    choice_1 = '1'
    choice_2 = '2'
    choice_3 = '3'
    choice_4 = '4'
    choice_5 = '5'
    CHOICES = (
        (choice_1,'Offensive/Abusive Material'),
        (choice_2,'Illicit Material'),
        (choice_3,'Personal Threats'),
        (choice_4,'Security Concern'),
        (choice_5,'Spam'),
    )
    report_choice = models.CharField(max_length=1,choices=CHOICES)
    comment = models.CharField(max_length = 300, blank=True)

    def __str__(self):
        return (f"Report From {self.author} to {self.post.author} at post : {self.post.id}")

    def save(self, **kwargs):
        super().save()

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from bootstrap_modal_forms.mixins import *
from crispy_forms.layout import *

class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content','image']

class ViewPostForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']

class NewPostForm(forms.Form):
    image = forms.ImageField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(widget=forms.HiddenInput)
    media = forms.FileField(widget=forms.HiddenInput, required=False)
    tags = forms.CharField(widget=forms.HiddenInput, required=False)

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['report_choice', 'comment']
        labels = {
        "report_choice": "What Does This Post Contain?",
        "comment" : "Additional Information"
        }
        help_texts = {
        "coverImage": ('Image will automatically be resized to 1500 x 300 pixels.'),
        "about": ('Write about yourself! Whatever describes you. ( 160 characters or less. )'),
        "quote": ('What is your current original idea? ( 80 characters or less. )'),
        }

class NewImage(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image']

blog/templates/blog/bottom_nav.html
{% load crispy_forms_tags %}
{% load static %}
{% load filters %}

<header class="site-header" >
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-bottom" style="background-color:white; border-top: 1px solid #a300cc;" >

        <a class="col" style="text-align:center; list-style-type: none; " id="hidden_interactt" href="{% url 'blog-home' %}">
          <img src="{% static 'resources/mobile/home.png' %}" style="width: 30px; height: 100%; text-align:center;"/>
        </a>

        <a class="col" style="text-align:center; list-style-type: none;" id="hidden_interactt" href="{% url 'notifications' %}">
        {% if notifications or requests %}
          <img src="{% static 'resources/mobile/bell_active.png' %}" style="width: 30px; height: 100%; text-align:center"/>
        {% else %}
          <img src="{% static 'resources/mobile/bell.png' %}" style="width: 30px; height: 100%; text-align:center"/>
        {% endif %}
        </a>

        <a class="col" style="text-align:center; list-style-type: none;" id="msgButton" href="{% url 'messages' %}">
          {% if unread_messages %}
          <img src="{% static 'resources/mobile/message_active.png' %}" style="width: 30px; height: 100%; text-align:center"/>
          {% else %}
          <img src="{% static 'resources/mobile/message.png' %}" style="width: 30px; height: 100%; text-align:center"/>
        {% endif %}
        </a>

        {% if post_page %}
        <a class="col post_new" style="text-align:center; list-style-type: none;" data-toggle="modal" data-target="#newPostModalCenter" href="{% url 'post-create' %}">
          <img class="align-middle" src="{% static 'resources/mobile/add.png' %}" style="width: 30px; height: 100%; text-align:center"/>
        </a>
        {% else %}
        <a class="col post_new" style="text-align:center; list-style-type: none;" href="{% url 'blog-home' %}">
          <img class="align-middle" src="{% static 'resources/mobile/add.png' %}" style="width: 30px;; height: 100%; text-align:center"/>
        </a>
        {% endif %}

  </nav>
</header>

blog/templates/blog/group_overhead.html
{% load crispy_forms_tags %}
{% load static %}
{% load filters %}

{% if not request.user_agent.is_mobile %}

<div class="thumbnail">
 <img class="img mb-2 rounded" style="width:100%; height:100%;" alt="Responsive image" src="{{group.groupsettings.coverImage.url}}">

  <div class="carousel-caption" style="">
        <a href="{% url 'group-posts' group.name %}">
      <img class="rounded-circle article-img mr-2" style=" width: 15vh; height: 15vh; border: 0.5vh solid #FFFFFF;" src="{{group.image.url}}">
      <div class="mb-0">
        <b><a class="mr-2" style="font-size:3vh; text-shadow: 1px 1px rgba(0, 0, 0, 0.5);">{{ group.name }}</a></b>
      </div>
      <div class="mb-0">
        {% if group.members.count > 1 %}
        <a class="text mr-2" style="font-size:2.25vh; text-shadow: 1px 1px rgba(0, 0, 0, 0.5);">{{ group.members.count }} Members</a>
        {% elif group.members.count > 0 %}
        <a class="text mr-2" style="font-size:2.25vh; text-shadow: 1px 1px rgba(0, 0, 0, 0.5);">{{ group.members.count }} Member</a>
        {% else %}
        <a class="text mr-2" style="font-size:2.25vh; text-shadow: 1px 1px rgba(0, 0, 0, 0.5);">No Members</a>
        {% endif %}
      </div>
 </a>
      <div>
        <main role="main" class="col">

          {% if is_member %}
            <button type="button" class="btn btn-primary float-right ml-2" id="leaveButton"
            style="color: #a300cc; background-color:white; border-color:white; border-radius:1rem;"><b>Leave</b></button>

          {% elif is_owner %}
            <button type="button" class="btn btn-primary float-right ml-2" id="editGroup" link="{% url 'group' group.name %}"
            style=" background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"
            href="{% url 'profile' %}"> <b>Edit Group</b> </button>

          {% else %}
                {% if group.type == "1" %}
                <button type="button" class="btn btn-primary float-right ml-2" id="joinButton"
                style="background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"><b>Join</b></button>
                {% endif %}

                {% if group.type == "2" or group.type == "3" %}
                  {% if is_following %}
                  <button type="button" class="btn btn-primary float-right ml-2" id="followButton"
                  style="color: #a300cc; background-color:white; border-color:white; border-radius:1rem;"><b>Unfollow</b></button>
                  {% else %}
                  <button type="button" class="btn btn-primary float-right ml-2" id="followButton"
                  style="background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"><b>Follow</b></button>
                  {% endif %}
                {% endif %}

                {% if group.type == "2" or group.type == "4" %}
                  {% if not existing_request %}
                  <button type="button" class="btn btn-primary float-right ml-2" id="sendRequestButton"
                  style="background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"><b>Request To Join</b></button>
                  {% else %}
                  <button type="button" class="btn btn-primary float-right ml-2"
                  style="color: #a300cc; background-color:white; border-color:white; border-radius:1rem;"><b>Request Sent</b></button>
                  {% endif %}
                {% endif %}
        {% endif %}

        </main>
      </div>
  </div>
 </div>


  {% else %}

  <div class="thumbnail" style="margin-bottom:20px;">
   <img class="img rounded" style="width:100%; height:100%;" alt="Responsive image" src="{{group.groupsettings.coverImage.url}}">

    <div class="carousel-caption" style="top:10px;">
     <a href="{% url 'group-posts' group.name %}" style="">
        <img class="rounded-circle article-img mr-0" style=" width: 12vh; height: 12vh; border: 0.5vh solid #FFFFFF;" src="{{group.image.url}}">
        <div class="mb-0">
          <b><a class="mr-0" style="font-size:3vh; color:black;">{{ group.name }}</a></b>
        </div>
        <div class="mb-0">
          {% if group.members.count > 1 %}
          <a class="text" style="font-size:2.25vh; color:black">{{ group.members.count }} Members</a>
          {% elif group.members.count > 0 %}
          <a class="text" style="font-size:2.25vh; color:black">{{ group.members.count }} Member</a>
          {% else %}
          <a class="text" style="font-size:2.25vh; color:black">No Members</a>
          {% endif %}
        </div>
     </a>
     </div>
        <div class="mb-0" style="text-align:center; margin-top:120px; margin-bottom:120px;">
          <main role="main" class="col mt-0" style="padding:0">
            {% if is_member %}
              <button type="button" class="btn btn-primary" id="leaveButton"
              style="color: #a300cc; background-color:white; border-color:white; border-radius:1rem;"><b>Leave</b></button>

            {% elif is_owner %}
              <button type="button" class="btn btn-primary" id="editGroup" link="{% url 'group' group.name %}"
              style=" background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"
              href="{% url 'profile' %}"> <b>Edit Group</b> </button>

            {% else %}
                  {% if group.type == "1" %}
                  <button type="button" class="btn btn-primary" id="joinButton"
                  style="background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"><b>Join</b></button>
                  {% endif %}

                  {% if group.type == "2" or group.type == "3" %}
                    {% if is_following %}
                    <button type="button" class="btn btn-primary" id="followButton"
                    style="color: #a300cc; background-color:white; border-color:white; border-radius:1rem;"><b>Unfollow</b></button>
                    {% else %}
                    <button type="button" class="btn btn-primary" id="followButton"
                    style="background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"><b>Follow</b></button>
                    {% endif %}
                  {% endif %}

                  {% if group.type == "2" or group.type == "4" %}
                    {% if not existing_request %}
                    <button type="button" class="btn btn-primary" id="sendRequestButton"
                    style="background-color: #a300cc; border-color: #a300cc; border-radius:1rem;"><b>Request To Join</b></button>
                    {% else %}
                    <button type="button" class="btn btn-primary"
                    style="color: #a300cc; background-color:white; border-color:white; border-radius:1rem;"><b>Request Sent</b></button>
                    {% endif %}
                  {% endif %}
          {% endif %}
          </main>

        </div>
   </div>

   <div id="group_info">
     {% if group.groupsettings.about %}
     <div class="mt-0 mb-2 ml-3 mr-3" id="about_section">
       <a class="text-secondary;" style="font-size:100%;">  {{group.groupsettings.about}}</a>
     </div>
     {% endif %}

     {% if group.groupsettings.quote %}
     <div class="mb-0 ml-3 mr-3" id="quote_section"
     style=" font-size:100%; text-align:left; ">
       <b class="text" style="color:#a300cc;">{{group.groupsettings.quote}}</b>
     </div>
     {% endif %}
   </div>

   <div class="mt-3">
      <div style="border-color:#a300cc; border-bottom: 2px solid #a300cc;">
        <div class="scrollmenu">

        <a class=" mr-0 mb-0" href="{% url 'group-posts' group.name 'feed' %}" style="color:black;">
          <b style="font-size:110%; color:#a300cc;"> Posts </b>
        </a>

        <a class=" mr-0 mb-0" href="{% url 'group-posts' group.name 'media' %}" style="color:black;">
          <b style="font-size:110%; color:#a300cc;"> Media </b>
        </a>

        <a class=" mr-0 mb-0" href="{% url 'group-posts' group.name 'owner' %}" style="color:black;">
          <b style="font-size:110%; color:#a300cc;"> Owner </b>
        </a>

        {% if group.members.count > 0 %}
        <a class=" mr-0 mb-0" href="{% url 'group-posts' group.name 'members' %}" style="color:black;">
           <b style="font-size:110%; color:#a300cc;"> Members {{group.members.count}} </b>
        </a>
        {% endif %}

        {% if group.followers.count > 0 %}
        <a class=" mr-0 mb-0" href="{% url 'group-posts' group.name 'followers' %}" style="color:black;">
          <b style="font-size:110%; color:#a300cc;;"> Followers {{group.followers.count}}</b>
        </a>
        {% endif %}

        </div>
      </div>
   </div>

  {% endif %}

blog/templates/blog/loading.html
<div style="display: inline; align-items: center; justify-content: center;">

    <div class="spinner">
      <div class="bounce1"></div>
      <div class="bounce2"></div>
      <div class="bounce3"></div>
    </div>

</div>

blog/templates/blog/loading_small.html
<div style="display: inline; align-items: center; justify-content: center;">

    <div class="spinner_small">
      <div class="bounce1"></div>
      <div class="bounce2"></div>
      <div class="bounce3"></div>
    </div>

</div>

blog/templates/blog/messages_mobile.html
{% extends "blog/base.html" %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}

{% block js_code %}
<script>
  $(document).ready(function(event) {
      $('#notifications_display').show();
      $('#requests_display').hide();
      $(document).on('click', '#requestButton' , function(event) {
        $('#notifications_display').hide();
        $('#requests_display').show();
      });

      $(document).on('click', '#notificationButton' , function(event) {
        $('#notifications_display').show();
        $('#requests_display').hide();
      });
  });

$(document).ready(function(event) {
  $('#chat_display').hide();
  $('#circles_loading_display').hide();
    $(document).on('click', '#message_chat' , function(event) {
      $('#circles_loading_display').show();
      $('#chat_display').show();
      $('#circles_display').hide();
      event.preventDefault();
      event.stopImmediatePropagation();
      var member_id = $(this).attr('member_id');
        $.ajax({
          type: "POST",
          url: "{% url 'blog-home' %}",
          data : { 'partner_id':member_id,'csrfmiddlewaretoken': '{{csrf_token}}', 'action' : "Open_Chat"},
          dataType: 'json',
          success : function(response) {
            $('#circles_loading_display').hide();
            $('#chat_display').html(response['form']);
          },
          error : function(rs, e) {
            console.log(rs.responseText);
          }
        });
    });
});

$(document).ready(function(event) {
    $(document).on('click', '#message_send' , function(event) {
      event.preventDefault();
      event.stopImmediatePropagation();
      var member_id = $(this).attr('member_id');
      var message = $('.message_content').val();
        $.ajax({
          type: "POST",
          url: "{% url 'blog-home' %}",
          data : { 'partner_id':member_id,'message':message,'csrfmiddlewaretoken': '{{csrf_token}}', 'action' : "Send_Chat"},
          dataType: 'json',
          success : function(response) {
            $('#chat_display').html(response['form']);
            console.log("success");
          },
          error : function(rs, e) {
            console.log(rs.responseText);
          }
        });
    });
});

$(document).ready(function(event) {
    $(document).on('click', '#delete_message_btn' , function(event) {
      event.preventDefault();
      event.stopImmediatePropagation();
      var message_id = $(this).attr('message_id');
      $("#message_bottom_btns").hide();
      $("#message_form_loading").show();
        $.ajax({
          type: "POST",
          url: "{% url 'blog-home' %}",
          data : { 'message_id':message_id,'csrfmiddlewaretoken': '{{csrf_token}}', 'action' : "Delete_Message"},
          dataType: 'json',
          success : function(response) {
            $('#chat_display').html(response['form']);
            console.log("success");
          },
          error : function(rs, e) {
            console.log(rs.responseText);
          }
        });
    });
});

$(document).ready(function(event) {
    $(document).on('click', '#backButton' , function(event) {
      $('#chat_display').hide();
      $('#circles_display').show();
      event.preventDefault();
      event.stopImmediatePropagation();
      $.ajax({
        type: "POST",
        url: "{% url 'blog-home' %}",
        data : { 'csrfmiddlewaretoken': '{{csrf_token}}', 'action' : "Load_Content"},
        dataType: 'json',
        success : function(response) {
          $("#circles_display").html(response['msg']);
          $('#chat_display').html("");
        },
        error : function(rs, e) {
          console.log(rs.responseText);
        }
      });
    });
});

</script>
{% endblock %}

{% block content %}

<div id="circles_display" >
{% include 'blog/messages_circles.html' %}
</div>

<div id="chat_display" >

</div>

<div id="circles_loading_display" >
  <article class="m-3 media-body" style="border-radius: 0.5rem; margin-bottom:0px;  background-color:white;">
    {% include 'blog/loading_small.html' %}
  <article>
</div>

{% endblock content %}

blog/templates/blog/post_like_comment.html
{% load crispy_forms_tags %}
{% load static %}
{% load filters %}

{#This is the part where the image information is done#}

<div class="" style="float:right">

  {% if p.reply != None %}
  <button class="updateButton" id="hidden_interact" member_id = {{p.reply.id}} reply_id = True
  style="cursor:pointer; border-radius: 1rem;">
  <img src="{% static 'resources/back.png' %}"
  style="width: 20px; height: 20px; border:none; cursor:pointer; display: inline-block;"></img>
  </button>
  {% endif %}

  <button class="updateButton" id="hidden_interact" member_id = {{p.id}}
  style="cursor:pointer; border-radius: 1rem;">
  {% if request.user.is_authenticated and p|has_reply:user%}
  <img src="{% static 'resources/comment_full.png' %}"
  style="width: 20px; height: 20px; border:none; cursor:pointer; display: inline-block;"></img>
  {% else %}
  <img src="{% static 'resources/comment.png' %}"
  style="width: 20px; height: 20px; border:none; cursor:pointer; display: inline-block;"></img>
  {% endif %}
  <a>{{p.post_set.count}}</a>
  </button>

  <button class="postLikeButton" id="hidden_interact" member_id = {{p.id}}
  style="cursor:pointer; border-radius: 1rem;">
  {% if request.user.is_authenticated and p|has_like:user%}
  <img src="{% static 'resources/heart_full.png' %}"
  style="width: 20px; height: 20px; border:none; cursor:pointer; display: inline-block;"></img>
  {% else %}
  <img src="{% static 'resources/heart.png' %}"
  style="width: 20px; height: 20px; border:none; cursor:pointer; display: inline-block;"></img>
  {% endif %}
  <a>{{p.like_set.count}}</a>
  </button>
</div>